---
title: "Lists - In Class Exercises"
author: "Dr. Shoemaker"
date: "DATA 2401"
output:nhtml_document

---

# Exercises: 

Make a list that contains the information on a single playing card. Suit, face, and value. 

```{r}
card <- list(
  suit = "clubs",
  face = "queen",
  value = 10
)


```


Make a second list where each element contains all the options for suit, face, and value, respectively. 

```{r}
allcards <- list( suits = c("hearts","diamonds","clubs", "spades"), face = c("ace","two","three","four","five","six","seven","eight","nine","ten","jack","queen","king","joker"), value = c(1,2,3,4,5,6,7,8,9,10,10,10,10,10))

```


If `Newlist <- list(a=1:10, b="Good morning", c="Hi")`, write an R statement that will add 1 to each element of the first vector in Newlist.

```{r}
Newlist <- list(a=1:10, b="Good morning", c="Hi")


```

If `b <- list(a=1:10, c="Hello", d="AA")`, write an R expression that will give all elements of the first vector of b, except the second, and write another that returns only elements of `a` that are greater than 7.

```{r}
b <- list(a=1:10, c="Hello", d="AA")

b$a[b$a > 7]

```

Let `x <- list(a=5:10, c="Hello", d="AA")`, write an R statement to add a new item z = "NewItem" to the list x.

```{r}
x <- list(a=5:10, c="Hello", d="AA")
x$z <- "NewItem"

```
